= Property-Based Testing for Stream Processing

Discussions on unit testing typically center on coverage, specifically statement coverage. Do the unit tests cover every
line of code? Even the most simple of methods or functions can have 100% statement coverage and still create serious production problems.

Test engineers (and application developers) tend to default to example-based tests, where one input scenario is tested. These
example-based tests are useful, but the "universe of possible inputs" could generate nondeterministic outputs - or, even worse, a runtime error. Property-based testing is a useful addition where a test suite can execute hundreds or thousands of test inputs, using every conceivable input that could break the method under test - empty collections, negative numbers, long strings, special characters, etc...

If the code passes a property-based test suite, you'll have a greater degree of confidence in the resiliency of that method
in the production environment.

== Applying the Paradigm to Data Pipelines

The asynchronous, distributed nature of stream processing codebases could greatly benefit from this type of resiliency testing.
Why? In most cases there's not a problem until there's a PROBLEM! Are these data pipelines processing events from multiple locales in several languages? What about data formats? Special characters? Null/empty values?

Let's take a swag at applying the principles of property-based testing to Apache Kafka-based stream processing applications
and topologies. We'll start with Kafka Streams, then attempt the same with Flink SQL. This is a Java example project. Therefore,
we'll use the https://jqwik.net/)[jqwik] framework to generate arbitrary objects as input events.

== Tooling

To use this repo, you'll need to the following tools installed:

* Java 17+
* Your favorite IDE or editor

You won't need Gradle installed, since we use the gradle-wrapper. But if you do, that's fine too.

== Running the Examples

To execute these unit tests just run this command. I like to use the `--info` switch to show some of what's happening during execution.

```shell
> ./gradlew test --info
```

To run a specific test, use the `--tests` switch with an identifier of the test class to run.

To run the `ShoutStreamsTest`:

```shell
> ./gradlew test --tests "*ShoutStreamsTest" --info

ShoutStreamsTest > testShout STANDARD_OUT
    timestamp = 2024-06-20T13:29:26.318131, ShoutStreamsTest:testShout =
                                  |-----------------------jqwik-----------------------
    tries = 1000                  | # of calls to property
    checks = 1000                 | # of not rejected calls
    generation = RANDOMIZED       | parameters are randomly generated
    after-failure = SAMPLE_FIRST  | try previously failed sample, then previous seed
    when-fixed-seed = ALLOW       | fixing the random seed is allowed
    edge-cases#mode = MIXIN       | edge cases are mixed in
    edge-cases#total = 7          | # of all combined edge cases
    edge-cases#tried = 7          | # of edge cases tried in current run
    seed = 5660301796215619896    | random seed to reproduce generated values

Gradle Test Executor 1 finished executing tests.

```

To run the `DeviceUserEnricherTest`:

```shell
> ./gradlew test --tests "*DeviceUserEnricherTest" --info
....
timestamp = 2024-06-18T14:13:52.089763, DeviceUserEnricherTest:testMatch =
                          	|-----------------------jqwik-----------------------
tries = 50                	| # of calls to property
checks = 50               	| # of not rejected calls
generation = RANDOMIZED   	| parameters are randomly generated
after-failure = SAMPLE_FIRST  | try previously failed sample, then previous seed
when-fixed-seed = ALLOW   	| fixing the random seed is allowed
edge-cases#mode = FIRST   	| edge cases are generated first
edge-cases#total = 50     	| # of all combined edge cases
edge-cases#tried = 50     	| # of edge cases tried in current run
seed = -8018840044203219213   | random seed to reproduce generated values
....
DeviceUserEnricherTest > testMiss STANDARD_OUT
    timestamp = 2024-06-20T13:32:03.089730, DeviceUserEnricherTest:testMiss =
                                  |-----------------------jqwik-----------------------
    tries = 50                    | # of calls to property
    checks = 50                   | # of not rejected calls
    generation = RANDOMIZED       | parameters are randomly generated
    after-failure = SAMPLE_FIRST  | try previously failed sample, then previous seed
    when-fixed-seed = ALLOW       | fixing the random seed is allowed
    edge-cases#mode = FIRST       | edge cases are generated first
    edge-cases#total = 50         | # of all combined edge cases
    edge-cases#tried = 50         | # of edge cases tried in current run
    seed = 1246033214940035466    | random seed to reproduce generated values



Gradle Test Executor 2 finished executing tests.
```